<a href="https://colab.research.google.com/github/Debajyoti137/iet_workshop/blob/main/iet_workshop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Welcome to Collab")
print("Numpy basics")

Welcome to Collab
Numpy basics


In [2]:
import numpy as np

# Single dimensional array

In [3]:
a= np.array([12,5,7,13,6,9,15,2,1])


In [4]:
a

array([12,  5,  7, 13,  6,  9, 15,  2,  1])

In [5]:
a.ndim

1

In [6]:
a.dtype

dtype('int64')

In [7]:
a.shape

(9,)

In [8]:
a1= np.array([12,5,7,13,6,9,15,2,1],dtype=np.int32)

In [9]:
a1.dtype

dtype('int32')

In [10]:
a2=a1.astype(np.int32)

In [11]:
a2.dtype

dtype('int32')

In [12]:
a2

array([12,  5,  7, 13,  6,  9, 15,  2,  1], dtype=int32)

In [13]:
a2[-1]

1

In [15]:
a2[len(a2)-1]

1

In [16]:
a2[2:6]

array([ 7, 13,  6,  9], dtype=int32)

In [17]:
a2[2:]

array([ 7, 13,  6,  9, 15,  2,  1], dtype=int32)

In [18]:
a2[:]

array([12,  5,  7, 13,  6,  9, 15,  2,  1], dtype=int32)

In [19]:
a2[1:7:2]

array([ 5, 13,  9], dtype=int32)

In [20]:
a2[::2]

array([12,  7,  6, 15,  1], dtype=int32)

In [21]:
a2[::-1]

array([ 1,  2, 15,  9,  6, 13,  7,  5, 12], dtype=int32)