<a href="https://colab.research.google.com/github/Debajyoti137/iet_workshop/blob/main/iet_workshop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
print("Welcome to Collab")
print("Numpy basics")

Welcome to Collab
Numpy basics


In [6]:
import numpy as np

# Single dimensional array

In [7]:
a= np.array([12,5,7,13,6,9,15,2,1])


In [8]:
a

array([12,  5,  7, 13,  6,  9, 15,  2,  1])

In [9]:
a.ndim

1

In [10]:
a.dtype

dtype('int64')

In [11]:
a.shape

(9,)

In [12]:
a1= np.array([12,5,7,13,6,9,15,2,1],dtype=np.int32)

In [9]:
a1.dtype

dtype('int32')

In [13]:
a2=a1.astype(np.int32)

In [14]:
a2.dtype

dtype('int32')

In [15]:
a2

array([12,  5,  7, 13,  6,  9, 15,  2,  1], dtype=int32)

In [16]:
a2[-1]

1

In [17]:
a2[len(a2)-1]

1

In [18]:
a2[2:6]

array([ 7, 13,  6,  9], dtype=int32)

In [19]:
a2[2:]

array([ 7, 13,  6,  9, 15,  2,  1], dtype=int32)

In [20]:
a2[:]

array([12,  5,  7, 13,  6,  9, 15,  2,  1], dtype=int32)

In [21]:
a2[1:7:2]

array([ 5, 13,  9], dtype=int32)

In [22]:
a2[::2]

array([12,  7,  6, 15,  1], dtype=int32)

In [23]:
a2[::-1]

array([ 1,  2, 15,  9,  6, 13,  7,  5, 12], dtype=int32)

In [24]:
a2[0:len(a2):-1]

array([], dtype=int32)

In [25]:
a2[-1:-len(a2)-1:-1]

array([ 1,  2, 15,  9,  6, 13,  7,  5, 12], dtype=int32)

In [26]:
a2[[1,3,6]] #special indexing

array([ 5, 13, 15], dtype=int32)

In [27]:
a3=np.random.randint(1,100,10)

In [28]:
a3

array([ 4, 10, 95, 83, 89, 96, 58, 75, 14, 34])

In [29]:
a3[a3>=50]

array([95, 83, 89, 96, 58, 75])

In [31]:
a3 >=50

array([False, False,  True,  True,  True,  True,  True,  True, False,
       False])

In [32]:
a3[[False, False,  True,  True,  True,  True,  True,  True, False,
       False]]

array([95, 83, 89, 96, 58, 75])

In [33]:
a3[(a3>=40) & (a3<=60)]

array([58])

In [34]:
a3[~((a3>=40) & (a3<=60))]

array([ 4, 10, 95, 83, 89, 96, 75, 14, 34])

In [36]:
a4=np.random.randint(1,100,10)
a5=np.random.randint(1,100,10)

In [37]:
a4

array([27, 16, 97, 79, 42, 64, 68, 67, 64, 28])

In [38]:
a5

array([ 7, 95, 27, 13,  6, 66, 21, 41, 12, 89])

In [39]:
a6=a4+a5

In [40]:
a6

array([ 34, 111, 124,  92,  48, 130,  89, 108,  76, 117])

In [41]:
np.sin(a6) #universal function

array([ 0.52908269, -0.86455145, -0.99568699, -0.77946607, -0.76825466,
       -0.93010595,  0.86006941,  0.92681851,  0.56610764, -0.68969794])

In [42]:
np.log10(a6)

array([1.53147892, 2.04532298, 2.09342169, 1.96378783, 1.68124124,
       2.11394335, 1.94939001, 2.03342376, 1.88081359, 2.06818586])

In [43]:
a6.sum()

929

In [44]:
a6

array([ 34, 111, 124,  92,  48, 130,  89, 108,  76, 117])

In [45]:
a6 +=10 #broadcasting

In [47]:
a6

array([ 44, 121, 134, 102,  58, 140,  99, 118,  86, 127])

Two D arrays

In [48]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [49]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
b.ndim

2

In [51]:
b.shape

(3, 3)

In [53]:
a7=np.arange(1,13)

In [54]:
a7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [55]:
b1=a7.reshape(3,4)

In [56]:
b1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
b2=a7.reshape(3,-1)

In [58]:
b2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [59]:
b3=a7.reshape(-1,4)

In [60]:
b3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [61]:
a7.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [62]:
a7.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])